/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YazarRehberiRouteImport } from './routes/yazar-rehberi'
import { Route as HakemSureciRouteImport } from './routes/hakem-sureci'
import { Route as EtikIlkelerRouteImport } from './routes/etik-ilkeler'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleIdRouteImport } from './routes/article.$id'

const YazarRehberiRoute = YazarRehberiRouteImport.update({
  id: '/yazar-rehberi',
  path: '/yazar-rehberi',
  getParentRoute: () => rootRouteImport,
} as any)
const HakemSureciRoute = HakemSureciRouteImport.update({
  id: '/hakem-sureci',
  path: '/hakem-sureci',
  getParentRoute: () => rootRouteImport,
} as any)
const EtikIlkelerRoute = EtikIlkelerRouteImport.update({
  id: '/etik-ilkeler',
  path: '/etik-ilkeler',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/etik-ilkeler': typeof EtikIlkelerRoute
  '/hakem-sureci': typeof HakemSureciRoute
  '/yazar-rehberi': typeof YazarRehberiRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/etik-ilkeler': typeof EtikIlkelerRoute
  '/hakem-sureci': typeof HakemSureciRoute
  '/yazar-rehberi': typeof YazarRehberiRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/etik-ilkeler': typeof EtikIlkelerRoute
  '/hakem-sureci': typeof HakemSureciRoute
  '/yazar-rehberi': typeof YazarRehberiRoute
  '/article/$id': typeof ArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/etik-ilkeler'
    | '/hakem-sureci'
    | '/yazar-rehberi'
    | '/article/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/etik-ilkeler'
    | '/hakem-sureci'
    | '/yazar-rehberi'
    | '/article/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/etik-ilkeler'
    | '/hakem-sureci'
    | '/yazar-rehberi'
    | '/article/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EtikIlkelerRoute: typeof EtikIlkelerRoute
  HakemSureciRoute: typeof HakemSureciRoute
  YazarRehberiRoute: typeof YazarRehberiRoute
  ArticleIdRoute: typeof ArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yazar-rehberi': {
      id: '/yazar-rehberi'
      path: '/yazar-rehberi'
      fullPath: '/yazar-rehberi'
      preLoaderRoute: typeof YazarRehberiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakem-sureci': {
      id: '/hakem-sureci'
      path: '/hakem-sureci'
      fullPath: '/hakem-sureci'
      preLoaderRoute: typeof HakemSureciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etik-ilkeler': {
      id: '/etik-ilkeler'
      path: '/etik-ilkeler'
      fullPath: '/etik-ilkeler'
      preLoaderRoute: typeof EtikIlkelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EtikIlkelerRoute: EtikIlkelerRoute,
  HakemSureciRoute: HakemSureciRoute,
  YazarRehberiRoute: YazarRehberiRoute,
  ArticleIdRoute: ArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
